/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "@app/custom-validators";
import {
  IsOptional,
  IsString,
  IsDate,
  ValidateNested,
  IsEnum,
  IsBoolean,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { Type } from "class-transformer";
import { EventLogUpdateManyWithoutEventsInput } from "./EventLogUpdateManyWithoutEventsInput";
import { EnumEventEventType } from "./EnumEventEventType";
import { EnumEventState } from "./EnumEventState";
import { UserUpdateManyWithoutEventsInput } from "./UserUpdateManyWithoutEventsInput";

@InputType()
class EventUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  dateDetails?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EventLogUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => EventLogUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => EventLogUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  eventLog?: EventLogUpdateManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    enum: EnumEventEventType,
  })
  @IsEnum(EnumEventEventType)
  @IsOptional()
  @Field(() => EnumEventEventType, {
    nullable: true,
  })
  eventType?: "oneDay" | "multiDay";

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  gallery?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  geoLocation?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  headerImage?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  location?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date;

  @ApiProperty({
    required: false,
    enum: EnumEventState,
  })
  @IsEnum(EnumEventState)
  @IsOptional()
  @Field(() => EnumEventState, {
    nullable: true,
  })
  state?: "draft" | "underReview" | "rejected" | "published";

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  status?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  volunteers?: UserUpdateManyWithoutEventsInput;
}

export { EventUpdateInput as EventUpdateInput };
